// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type IndexDocumentDataSlicesSlice =
  | ContactGatewaySlice
  | ProjectGallerySlice
  | BioHighlightedFeaturesSlice
  | HeroIntroSlice;

/**
 * Content for index documents
 */
interface IndexDocumentData {
  /**
   * Slice Zone field in *index*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: index.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<IndexDocumentDataSlicesSlice>; /**
   * Meta Title field in *index*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: index.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *index*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: index.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *index*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: index.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * index document from Prismic
 *
 * - **API ID**: `index`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IndexDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<IndexDocumentData>, "index", Lang>;

export type AllDocumentTypes = IndexDocument;

/**
 * Item in *BioHighlightedFeatures → With Video and Features → Primary → Technology Tags*
 */
export interface BioHighlightedFeaturesSliceWithVideoAndFeaturesPrimaryTechnologyTagsItem {
  /**
   * Tag field in *BioHighlightedFeatures → With Video and Features → Primary → Technology Tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_highlighted_features.with_video_and_features.primary.technology_tags[].tag
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tag: prismic.KeyTextField;
}

/**
 * Item in *BioHighlightedFeatures → With Video and Features → Primary → Feature List*
 */
export interface BioHighlightedFeaturesSliceWithVideoAndFeaturesPrimaryFeatureListItem {
  /**
   * Feature Title field in *BioHighlightedFeatures → With Video and Features → Primary → Feature List*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_highlighted_features.with_video_and_features.primary.feature_list[].feature_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  feature_title: prismic.RichTextField;

  /**
   * Feature Icon field in *BioHighlightedFeatures → With Video and Features → Primary → Feature List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_highlighted_features.with_video_and_features.primary.feature_list[].feature_icon
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  feature_icon: prismic.KeyTextField;

  /**
   * Feature Description field in *BioHighlightedFeatures → With Video and Features → Primary → Feature List*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_highlighted_features.with_video_and_features.primary.feature_list[].feature_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  feature_description: prismic.RichTextField;
}

/**
 * Primary content in *BioHighlightedFeatures → With Video and Features → Primary*
 */
export interface BioHighlightedFeaturesSliceWithVideoAndFeaturesPrimary {
  /**
   * Title field in *BioHighlightedFeatures → With Video and Features → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_highlighted_features.with_video_and_features.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * SubTitle field in *BioHighlightedFeatures → With Video and Features → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_highlighted_features.with_video_and_features.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;

  /**
   * intro_media field in *BioHighlightedFeatures → With Video and Features → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_highlighted_features.with_video_and_features.primary.intro_media
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  intro_media: prismic.KeyTextField;

  /**
   * Intro Caption field in *BioHighlightedFeatures → With Video and Features → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_highlighted_features.with_video_and_features.primary.intro_caption
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  intro_caption: prismic.KeyTextField;

  /**
   * Intro Description field in *BioHighlightedFeatures → With Video and Features → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_highlighted_features.with_video_and_features.primary.intro_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  intro_description: prismic.RichTextField;

  /**
   * Profile Highlight field in *BioHighlightedFeatures → With Video and Features → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_highlighted_features.with_video_and_features.primary.profile_highlight
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  profile_highlight: prismic.RichTextField;

  /**
   * Profile Summary field in *BioHighlightedFeatures → With Video and Features → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_highlighted_features.with_video_and_features.primary.profile_summary
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  profile_summary: prismic.RichTextField;

  /**
   * Technology Tags field in *BioHighlightedFeatures → With Video and Features → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_highlighted_features.with_video_and_features.primary.technology_tags[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  technology_tags: prismic.GroupField<
    Simplify<BioHighlightedFeaturesSliceWithVideoAndFeaturesPrimaryTechnologyTagsItem>
  >;

  /**
   * Feature List field in *BioHighlightedFeatures → With Video and Features → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: bio_highlighted_features.with_video_and_features.primary.feature_list[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  feature_list: prismic.GroupField<
    Simplify<BioHighlightedFeaturesSliceWithVideoAndFeaturesPrimaryFeatureListItem>
  >;
}

/**
 * With Video and Features variation for BioHighlightedFeatures Slice
 *
 * - **API ID**: `with_video_and_features`
 * - **Description**: Displays an embedded video with caption, profile text with technology tags, and a grid of featured principles or capabilities.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BioHighlightedFeaturesSliceWithVideoAndFeatures =
  prismic.SharedSliceVariation<
    "with_video_and_features",
    Simplify<BioHighlightedFeaturesSliceWithVideoAndFeaturesPrimary>,
    never
  >;

/**
 * Slice variation for *BioHighlightedFeatures*
 */
type BioHighlightedFeaturesSliceVariation =
  BioHighlightedFeaturesSliceWithVideoAndFeatures;

/**
 * BioHighlightedFeatures Shared Slice
 *
 * - **API ID**: `bio_highlighted_features`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BioHighlightedFeaturesSlice = prismic.SharedSlice<
  "bio_highlighted_features",
  BioHighlightedFeaturesSliceVariation
>;

/**
 * Item in *ContactGateway → Form Unavailable with Direct Links → Primary → Contact Methods Panel*
 */
export interface ContactGatewaySliceFormUnavailableSplitPanelPrimaryContactMethodsPanelItem {
  /**
   * Contact Links field in *ContactGateway → Form Unavailable with Direct Links → Primary → Contact Methods Panel*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_gateway.form_unavailable_split_panel.primary.contact_methods_panel[].contact_links
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  contact_links: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Icon Only" | "Icon and Text"
    >
  >;
}

/**
 * Primary content in *ContactGateway → Form Unavailable with Direct Links → Primary*
 */
export interface ContactGatewaySliceFormUnavailableSplitPanelPrimary {
  /**
   * Badge field in *ContactGateway → Form Unavailable with Direct Links → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_gateway.form_unavailable_split_panel.primary.badge
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  badge: prismic.RichTextField;

  /**
   * Main Title field in *ContactGateway → Form Unavailable with Direct Links → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_gateway.form_unavailable_split_panel.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *ContactGateway → Form Unavailable with Direct Links → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_gateway.form_unavailable_split_panel.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Contact Methods Panel field in *ContactGateway → Form Unavailable with Direct Links → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_gateway.form_unavailable_split_panel.primary.contact_methods_panel[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  contact_methods_panel: prismic.GroupField<
    Simplify<ContactGatewaySliceFormUnavailableSplitPanelPrimaryContactMethodsPanelItem>
  >;
}

/**
 * Form Unavailable with Direct Links variation for ContactGateway Slice
 *
 * - **API ID**: `form_unavailable_split_panel`
 * - **Description**: Displays the main heading, context, form status message with short explanation, and a panel offering alternative contact methods via external profiles or email links, structured as two panels side by side.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactGatewaySliceFormUnavailableSplitPanel =
  prismic.SharedSliceVariation<
    "form_unavailable_split_panel",
    Simplify<ContactGatewaySliceFormUnavailableSplitPanelPrimary>,
    never
  >;

/**
 * Slice variation for *ContactGateway*
 */
type ContactGatewaySliceVariation =
  ContactGatewaySliceFormUnavailableSplitPanel;

/**
 * ContactGateway Shared Slice
 *
 * - **API ID**: `contact_gateway`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactGatewaySlice = prismic.SharedSlice<
  "contact_gateway",
  ContactGatewaySliceVariation
>;

/**
 * Primary content in *HeroIntro → Default → Primary*
 */
export interface HeroIntroSliceDefaultPrimary {
  /**
   * Intro Label field in *HeroIntro → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_intro.default.primary.intro_label
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  intro_label: prismic.RichTextField;

  /**
   * Headline field in *HeroIntro → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_intro.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  headline: prismic.RichTextField;

  /**
   * Subtitle field in *HeroIntro → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_intro.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Description field in *HeroIntro → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_intro.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * CTA Buttons field in *HeroIntro → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_intro.default.primary.cta_buttons
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_buttons: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "default" | "secondary"
    >
  >;

  /**
   * Social/Profile Links field in *HeroIntro → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_intro.default.primary.social_links
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  social_links: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "GitHub" | "LinkedIn"
    >
  >;
}

/**
 * Default variation for HeroIntro Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero with title, subtitle, description, two call-to-action buttons, and a social links row.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroIntroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroIntroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroIntro*
 */
type HeroIntroSliceVariation = HeroIntroSliceDefault;

/**
 * HeroIntro Shared Slice
 *
 * - **API ID**: `hero_intro`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroIntroSlice = prismic.SharedSlice<
  "hero_intro",
  HeroIntroSliceVariation
>;

/**
 * Item in *ProjectGallery → Default → Primary → Projects*
 */
export interface ProjectGallerySliceDefaultPrimaryProjectsItem {
  /**
   * media field in *ProjectGallery → Default → Primary → Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_gallery.default.primary.projects[].media
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  media: prismic.KeyTextField;

  /**
   * Title field in *ProjectGallery → Default → Primary → Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_gallery.default.primary.projects[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Summary field in *ProjectGallery → Default → Primary → Projects*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_gallery.default.primary.projects[].summary
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  summary: prismic.RichTextField;

  /**
   * badges field in *ProjectGallery → Default → Primary → Projects*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project_gallery.default.primary.projects[].badges
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  badges: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Preview Link field in *ProjectGallery → Default → Primary → Projects*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project_gallery.default.primary.projects[].preview_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  preview_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Code Link field in *ProjectGallery → Default → Primary → Projects*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project_gallery.default.primary.projects[].code_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  code_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *ProjectGallery → Default → Primary*
 */
export interface ProjectGallerySliceDefaultPrimary {
  /**
   * Heading field in *ProjectGallery → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_gallery.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *ProjectGallery → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_gallery.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Projects field in *ProjectGallery → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project_gallery.default.primary.projects[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  projects: prismic.GroupField<
    Simplify<ProjectGallerySliceDefaultPrimaryProjectsItem>
  >;
}

/**
 * Default variation for ProjectGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard project gallery layout with section heading, description, and grid of project cards featuring media, text, badges, and action buttons.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectGallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectGallerySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectGallery*
 */
type ProjectGallerySliceVariation = ProjectGallerySliceDefault;

/**
 * ProjectGallery Shared Slice
 *
 * - **API ID**: `project_gallery`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectGallerySlice = prismic.SharedSlice<
  "project_gallery",
  ProjectGallerySliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      IndexDocument,
      IndexDocumentData,
      IndexDocumentDataSlicesSlice,
      AllDocumentTypes,
      BioHighlightedFeaturesSlice,
      BioHighlightedFeaturesSliceWithVideoAndFeaturesPrimaryTechnologyTagsItem,
      BioHighlightedFeaturesSliceWithVideoAndFeaturesPrimaryFeatureListItem,
      BioHighlightedFeaturesSliceWithVideoAndFeaturesPrimary,
      BioHighlightedFeaturesSliceVariation,
      BioHighlightedFeaturesSliceWithVideoAndFeatures,
      ContactGatewaySlice,
      ContactGatewaySliceFormUnavailableSplitPanelPrimaryContactMethodsPanelItem,
      ContactGatewaySliceFormUnavailableSplitPanelPrimary,
      ContactGatewaySliceVariation,
      ContactGatewaySliceFormUnavailableSplitPanel,
      HeroIntroSlice,
      HeroIntroSliceDefaultPrimary,
      HeroIntroSliceVariation,
      HeroIntroSliceDefault,
      ProjectGallerySlice,
      ProjectGallerySliceDefaultPrimaryProjectsItem,
      ProjectGallerySliceDefaultPrimary,
      ProjectGallerySliceVariation,
      ProjectGallerySliceDefault,
    };
  }
}
