// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  bio_highlighted_features: dynamic(() => import("./BioHighlightedFeatures")),
  contact_gateway: dynamic(() => import("./ContactGateway")),
  hero_intro: dynamic(() => import("./HeroIntro")),
  project_gallery: dynamic(() => import("./ProjectGallery")),
};
